export const mockInstruments = [
  {
    id: 'gbpjpy',
    symbol: 'GBP/JPY',
    name: 'British Pound vs Japanese Yen',
    flag: '🇬🇧🇯🇵',
    bid: 193.221,
    ask: 193.231,
    change: 0.123,
    changePercent: 0.064,
    isFavorite: true,
  },
  {
    id: 'btc',
    symbol: 'BTC',
    name: 'Bitcoin',
    flag: '₿',
    bid: 110893.32,
    ask: 110911.32,
    change: 1250.45,
    changePercent: 1.15,
    isFavorite: true,
  },
  {
    id: 'xauusd',
    symbol: 'XAU/USD',
    name: 'Gold vs US Dollar',
    flag: '🥇🇺🇸',
    bid: 3738.635,
    ask: 3738.795,
    change: -12.45,
    changePercent: -0.33,
    isFavorite: false,
  },
  {
    id: 'usdjpy',
    symbol: 'USD/JPY',
    name: 'US Dollar vs Japanese Yen',
    flag: '🇺🇸🇯🇵',
    bid: 149.221,
    ask: 149.231,
    change: -0.003,
    changePercent: -0.002,
    isFavorite: true,
  },
  {
    id: 'aapl',
    symbol: 'AAPL',
    name: 'Apple Inc',
    flag: '🍎',
    bid: 252.65,
    ask: 252.85,
    change: -1.25,
    changePercent: -0.49,
  },
  {
    id: 'eurusd',
    symbol: 'EUR/USD',
    name: 'Euro vs US Dollar',
    flag: '🇪🇺🇺🇸',
    bid: 1.17004,
    ask: 1.17012,
    change: 0.0023,
    changePercent: 0.20,
  },
  {
    id: 'gbpusd',
    symbol: 'GBP/USD',
    name: 'British Pound vs US Dollar',
    flag: '🇬🇧🇺🇸',
    bid: 1.33838,
    ask: 1.33848,
    change: 0.0045,
    changePercent: 0.34,
  },
  {
    id: 'ustec',
    symbol: 'USTEC',
    name: 'US Tech 100',
    flag: '📈',
    bid: 24356.98,
    ask: 24357.68,
    change: -125.45,
    changePercent: -0.51,
  },
  {
    id: 'usoil',
    symbol: 'USOIL',
    name: 'US Oil',
    flag: '🛢️',
    bid: 64.312,
    ask: 64.330,
    change: 0.89,
    changePercent: 1.40,
  },
];

export const getWebSocketUrl = () => {
  const streams = mockInstruments.map(instrument => {
    const symbol = instrument.symbol.replace('/', '').toLowerCase();
    return `${symbol}@trade`;
  }).join('/');
  return `wss://stream.binance.com:9443/stream?streams=${streams}`;
};
